[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = [
    "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))",
    "./gradlew build -x test"
]

[start]
cmd = "java -jar build/libs/*.jar"